const htmlPdf = require('html-pdf-node');

module.exports = async (req, res) => {
  try {
    // Handle GET -> show test HTML page
    if (req.method === "GET") {
      return res.status(200).send(`
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <title>PDF Generator Test</title>
        </head>
        <body>
          <h1>Hello Sir Isaac0yen 🚀</h1>
          <p>This is a test page for your <b>HTML → PDF API</b> running on Vercel.</p>
          <form method="POST" action="/" style="margin-top:20px;">
            <textarea name="html" rows="8" cols="60"><h2>PDF Test</h2><p>This is generated by html-pdf-node on Vercel!</p></textarea><br/>
            <button type="submit">Generate PDF</button>
          </form>
        </body>
        </html>
      `);
    }

    // Handle POST -> generate PDF
    if (req.method === "POST") {
      let html;

      if (req.headers["content-type"]?.includes("application/json")) {
        html = req.body?.html;
      } else {
        html = req.body?.html || "";
      }

      if (!html) {
        return res.status(400).json({ error: "Missing HTML input" });
      }

      const options = { 
        format: 'A4',
        printBackground: true,
        margin: { top: '20px', bottom: '20px', left: '20px', right: '20px' }
      };

      const file = { content: html };
      
      const pdfBuffer = await htmlPdf.generatePdf(file, options);

      res.setHeader("Content-Type", "application/pdf");
      res.setHeader("Content-Disposition", "attachment; filename=output.pdf");
      return res.status(200).send(pdfBuffer);
    }

    // Invalid method
    res.setHeader("Allow", ["GET", "POST"]);
    return res.status(405).json({ error: `Method ${req.method} Not Allowed` });
  } catch (err) {
    console.error("PDF generation error:", err);
    return res.status(500).json({ 
      error: "Failed to generate PDF", 
      details: err.message
    });
  }
};
